# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    email_provider_username: <%= ENV["skyi"] %>
    email_provider_password: <%= ENV["Wc2Mailchimp.com"] %>
    mailchimp_api_key: <%= ENV["d8f67007791b2022935300098f264842-us8"] %>
    mailchimp_list_id: <%= ENV["440125"] %>
    domain_name: whatismurmur.com
    owner_email: <%= ENV["yi.simon.k@gmail.com"] %>
    secret_key_base: bd79cca32442ebbd3979d12979183c23fd5957fd99463bde13318b897a7fae25e6d0afffce0a8d2f61b3b9d08c2af8e82db6e0459aa680b79cfbf6b32bd1e420

test:
  secret_key_base: 86c1baa202347227463b0688a72761a9eda071b51283e94086a163e8df3ea9f9897b2fd5cf6d3642b7d4ac8baf1ce94ad5179da4ce244c012e8476508a18d767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
